version: "2"
services:

  base:
    build: base
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  glibc:
    build: glibc
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
