# Alpine Linux php7

FROM youske/alpine-stdmachine:base
MAINTAINER youske miyakoshi <youske@gmail.com>

LABEL com.stdmachine.description="alpine php7 image" \
      com.stdmachine.role="php7 image"

RUN apk add --no-cache php7

#composer setuo
