# Alpine Linux julia

FROM youske/alpine-stdmachine:base
MAINTAINER youske miyakoshi <youske@gmail.com>

LABEL com.stdmachine.description="alpine lua image" \
      com.stdmachine.role="lua image"

RUN apk add --no-cache julia

#composer setuo
