# Alpine Linux julia

FROM youske/alpine-stdmachine:base
MAINTAINER youske miyakoshi <youske@gmail.com>

LABEL com.stdmachine.description="alpine julia image" \
      com.stdmachine.role="julia image"

RUN apk add --no-cache julia

#composer setuo
