# Alpine Linux php5

FROM youske/alpine-stdmachine:base
MAINTAINER youske miyakoshi <youske@gmail.com>

LABEL com.stdmachine.description="alpine php5 image" \
      com.stdmachine.role="php5 image"

RUN apk add --no-cache php5

#composer setuo
